### ISSUE TITLE
Surface Book: power and volume buttons not working / clipboard detach triggers power button

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#243]
Besides not working, they are not present in /proc/bus/input/devices.
Not sure what debug information would be helpful.

**Comment by qzed** [comment]
Surface Book 1 or 2? Also do they just not show up in the device list or are they also not working?

On the Surface Book 2, the buttons actually work with two virtual `gpio-keys` devices (one for the power button and one for the volume buttons) as they are provided by the device via GPIO interrupts. So you will see them there under the name `gpio-keys`.

**Comment by tmarkov** [comment]
The original (I believe officially it's just Surface Book, not Surface Book 1). As per title, they are not working.

**Comment by qzed** [comment]
Okay, had to make sure because this is a bit special on the SB2. I can't really help you with the SB(1) though, sorry (I don't own one). If you haven't you could look if there is anything interesting related to the ACPI in the dmesg log, but that's just a guess. AFAIK the buttons on the SB(1) should already work with the upstream kernel, maybe you could try and see if this is also a problem upstream.

**Comment by ChenglongWang** [comment]
I found that SB/SB2 are really Linux unfriendly laptops. Thanks so much for the effort towards this project, but did not help much with the critical problem of the Linux on SB series. 
Most common functions already work with the default kernel. I think the battery indicator, touchpad gesture(multi-finger) are really important. Besides, the dedicated Nvidia GPU problem did not be fixed on my SB2, and CPU or maybe GPU usage is really poorly-controlled that makes the machine overheated.

**Comment by tmarkov** [comment]
Here's a dmesg from Jakedays's 4.18.2: 
[dmesg.txt](https://github.com/jakeday/linux-surface/files/2384515/dmesg.txt)

**Comment by tmarkov** [comment]
I tested on 4.17. Buttons don't work there, too, so I guess this https://github.com/jakeday/linux-surface/issues/236 is still relevant.

**Comment by florianmw** [comment]
I'm having the same issue on Surface Pro 2017. In my case the buttons were working correctly with 4.17.

**Comment by florianmw** [comment]
#252 seems to solve it.

**Comment by qzed** [comment]
@florianmw #252 should not contain any significant changes. On the SB2 the buttons also work with the previous module, which has not changed from 4.17. I'm not sure why they didn't work on the SP17, but it's nice to see that they work with the PR. Also #252 is only relevant for SB2 and SP17 (but may affect SP4).

The SB issue should be an upstream issue. I can't find any related code or changes of @jakeday related to them.

@tmarkov I can't see anything directly indicating a problem in the dmesg log, but on the other hand I'm not familiar with the SB. If you feel up to it you could look at the DSDT and track down the driver relevant for the buttons.

**Comment by florianmw** [comment]
@qzed may there be some fixes upstream? I used 4.18.9 instead of 4.18.7 (which Jake Day used to compile).

**Comment by qzed** [comment]
@florianmw As far as I can see, the SB2 and SP17 are identical with regards to the buttons, so I should have noticed the same problem on the SB2. I can't say for certain, but I don't think it's an upstream issue on the SP17. On the other hand, ACPI sometimes seems to do weird things (still don't know where #220 came from).

**Comment by jakeday** [comment]
Marking as resolved in 4.18.11.

**Comment by tmarkov** [comment]
But it isn't.

**Comment by jasonmoofang** [comment]
Also seeing it here. Original Surface Book, power/volume buttons do not work in 4.18.7 nor 4.18.11.

**Comment by mickforum** [comment]
@jakeday hi, sorry but still not working here (surface book 2015). tell us if you need debbug files...

**Comment by Y05H10** [comment]
@jakeday +1 on 4.18.16

**Comment by mickforum** [comment]
I've compiled the kernel (4.18.20)  without the button.patch. everything ok, buttons are back...
thanks

**Comment by qzed** [comment]
@mickforum Can you send me a DSDT so I can check what's going wrong?

**Comment by kitakar5525** [comment]
I can also confirm that buttons are not working on SB1 with Performance Base if kernel is compiled with 0003-buttons.patch.

Here is decompiled DSDT from mine:
- [Disassembled DSDT from Surface Book 1 with Performance Base i7/16GB/512GB/GTX965M](https://gist.github.com/kitakar5525/7221bd545cbea68ef228ef8d9071b4d5)

**Comment by qzed** [comment]
Thanks!

Pretty much as I expected, the SB1 uses the same device identifiers (`VGBI`/`MSHW0040`) for the power button, and the GPIOs registered under it are used for the base state. As far as I can see, the right way to differentiate between them is to use the `OMPR` (OEM Platform Revision) which can be queried with the `DSM` in the newer devices (5th gen.) but not in the SB1. This should be `5` for 5th generation devices etc., but there's some testing required to make sure it doesn't break things for other devices.
