### ISSUE TITLE
Ethernet does not work on Surface Dock (SB with Performance Base, any kernel)

### ISSUE THREAD

**Issue by muratkemaldar** [jakeday/linux-surface#247]
Hey, 

I have a Surface Book 1 with Performance Base (i7), and a Surface Dock (brick), but the Ethernet slot on the dock doesn't work. I can see that Ubuntu 18.04 recognizes the adapter / driver (using ifconfig), but I do not get a connection, which I do on Windows 10.

I have tried different kernels, 4.13, 4.15, 4.17, and the recent 4.18, but none of them work.
This is the only issue I have.

Anyone else having this issue? What can I do?
This is what it says on the ifconfig:

> enxbc8385f8358d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether bc:83:85:f8:35:8d  txqueuelen 1000  (Ethernet)
        RX packets 1231  bytes 60335 (60.3 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 266  dropped 0 overruns 0  carrier 0  collisions 0

Kind regards,
Murat

**Comment by qzed** [comment]
Possible duplicate of #105 and #70. Apparently this is an upstream bug, AFAIK at least for the newer docks with product ID `07c6`. I'm not sure if this is also supposed to affect the older dock version, so you might want to check that.

**Comment by muratkemaldar** [comment]
I updated my Surface Dock to the latest version a few weeks ago (via Surface Dock Updater), hoping it would fix this Ethernet issue, but unfortunately it didn't. 

I couldn't find any product ID on my Surface Dock.

**Comment by qzed** [comment]
Sorry, you can find that out by running `lsusb`. The output should be something along the lines of
```
Bus XXX Device XXX: ID VVVV:PPPP Some name
```
Where `PPPP` is the product ID. There should be one line with the name Microsoft Surface Dock Ethernet (or something like this, I can't check this at the moment, sorry).

If that ID is `07c6`, then it's definitely the same problem as in the two issues linked above.

**Comment by muratkemaldar** [comment]
Yeah, seems I have a device with that product ID.
`Bus 002 Device 005: ID 045e:07c6 Microsoft Corp.`

Will checkout the other tickets, thank you.

**Comment by denzilferreira** [comment]
Patch is here: http://patchwork.ozlabs.org/patch/745362/

**Comment by muratkemaldar** [comment]
Hey @denzilferreira , sounds good!
But I am a bit lost and don't know what to do exactly with that patch, or how to proceed.

Does it mean I have to compile the kernel from source (like in the README) and install a new kernel, or can I apply the patch to my running system (4.18) somehow?

**Comment by jakeday** [comment]
Fixed in 4.18.11.

**Comment by qzed** [comment]
Still fails for me with
```
r8152 2-4.2:1.0 enx2816a8049da6: Stop submitting intr, status -71
```
Does this work for anyone?

**Comment by hadrienk** [comment]
I have seen it working a couple of time but it is very rare.

**Comment by hadrienk** [comment]
Tried again with kernel version 4.18.16. Still doesn't work.

**Comment by hadrienk** [comment]
Does not work with mainline either.

**Comment by qzed** [comment]
Let's handle this in #259.
