### ISSUE TITLE
[5th Gen Devices] WiFi issues (slow/unreliable)

### ISSUE THREAD

**Issue by Fireobridy** [jakeday/linux-surface#267]
I am using kernel 4.17.3-surface-linux-surface and i am getting only something between 10 and 25kByte/s throughput on my surface pro 2017. It doesent matter if i am near the accesspoint or not. I made various web based speed tests but also looked at apt-get upgrade. Any tipps are welcome.

**Comment by xaviervilla** [comment]
Does this issue occur on the latest kernel?

**Comment by Fireobridy** [comment]
`june@yellow-scout:~$ lspci -k | grep -A 5 Ethernet
01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
	Subsystem: Device 0008:045e
	Kernel driver in use: mwifiex_pcie
	Kernel modules: mwifiex_pcie
02:00.0 Non-Volatile memory controller: Intel Corporation Device f1a5 (rev 03)
	Subsystem: Intel Corporation Device 390a
june@yellow-scout:~$ iwconfig
lo        no wireless extensions.

wlp1s0    IEEE 802.11  ESSID:"replaced"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: XX:XX:XX:XX:XX:XX   
          Bit Rate=144.4 Mb/s   Tx-Power=14 dBm   
          Retry short limit:9   RTS thr=2347 B   Fragment thr=2346 B   
          Power Management:off
          Link Quality=70/70  Signal level=-39 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

june@yellow-scout:~$ wget https://speed.hetzner.de/100MB.bin
--2018-10-07 16:43:19--  https://speed.hetzner.de/100MB.bin
Auflösen des Hostnamens speed.hetzner.de (speed.hetzner.de) … 2a01:4f8:0:59ed::2, 88.198.248.254
Verbindungsaufbau zu speed.hetzner.de (speed.hetzner.de)|2a01:4f8:0:59ed::2|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 104857600 (100M) [application/octet-stream]
Wird in »100MB.bin« gespeichert.

100MB.bin                           2%[>                                                            ]   2,94M  16,4KB/s    ETA 2h 5m  
`

I didn't try the newest kernel.

**Comment by oleid** [comment]
I assume you're using the latest WiFi firmware? 
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Fireobridy** [comment]
> 
> I assume you're using the latest WiFi firmware?

Yes i do. Just to make sure i downloaded the firmware from the repository and copied it over the existing. No improvement so far.

**Comment by xaviervilla** [comment]
From the output, things look normal but yea, I was getting ~ 3.7Mb/s with `wget https://speed.hetzner.de/100MB.bin` from US. Can you try booting into another kernel, perhaps the generic kernel and testing the throughput? You can do so from the 'advanced settings' options from the Grub Bootloader.

**Comment by fxmy** [comment]
Surface Book 2 here. what I'm experiencing here is, WIFI is a __lot__ faster if I connect to my Bluetooth mouse. The difference could vary from 200K/s to 3.5M/s on the same access point.

```
 fxmy@Surface2  ~  lspci -k | grep -A 5 Ethernet
01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
        Subsystem: Device 0007:045e
        Kernel driver in use: mwifiex_pcie
        Kernel modules: mwifiex_pcie
02:00.0 3D controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
        Subsystem: Microsoft Corporation GP106M [GeForce GTX 1060 Mobile]
 fxmy@Surface2  ~  uname -r
4.18.7-surface-linux-surface
```

**Comment by qzed** [comment]
I haven't really looked into this, but this might be some sort of power management issue. Considering this:

> WIFI is a lot faster if I connect to my Bluetooth mouse

it could make sense, as it's basically the same board doing both. Jake [mentioned](https://github.com/jakeday/linux-surface/issues/274#issuecomment-450418186) that he's disabling powersave in the wifi-module, so this might fix it.

**Comment by nkkollaw** [comment]
Yup. Seems to be related to that. Using the mouse "wakes up" whatever component is misbehaving, and the thing starts working again.

I did try disabling power management via something like `sudo iwconfig wlan0 power off`, but it had no effect (if I issue `iwconfig` it does say that power management is off).

**Comment by jakeday** [comment]
This is fixed in the 4.18.20 releases.

**Comment by nkkollaw** [comment]
Are you sure you are actually running that kernel? 

`uname -r`

**Comment by skywideopen** [comment]
Yes:

`4.18.20-surface-linux-surface`

**Comment by nkkollaw** [comment]
Yes, I had the same impression actually. I use my mouse virtually the whole time.

**Comment by nkkollaw** [comment]
OK, I can confirm that I'm still experiencing this problem.

@jakeday, I think this issue should be reopened.

**Comment by fellnerse** [comment]
It's slow for me as well. Just upgraded to 4.18.20.

**Comment by csanjust** [comment]
Same problem here with kernel 5.0.10-surface-linux-surface. Disabling power management with "sudo iwconfig wlan0 power off" doesn't help. The speed drops to 0.5 Mbps, but using my bluetooth mouse I can reach 15 Mbps.  In any case the speed under Windows, with the same connection is about 30 Mbps.

**Comment by nkkollaw** [comment]
I have no idea why this issue is closed. @jakeday, I think this issue should be re-opened, since it's not been fixed.

The internet is pretty important nowadays...

**Comment by Sidiox** [comment]
Can confirm that on `5.1.15-surface-linux-surface` on SP3 the issue persists, regardless of powersave mode 2/3 in network manager. Attaching a bluetooth device indeed fixes the issue here.

**Comment by k0pernicus** [comment]
Got the same problem: bluetooth device fixed the issue here.
I just checked my NetworkConfiguration (in /etc/NetworkManager/NetworkManager.conf), and there is nothing fancy here:

```
[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq
dhcp=dhclient

[ifupdown]
managed=true

[device]
wifi.scan-rand-mac-address=false
``` 
Also, in `/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf`:

```
[connection]
wifi.powersave = 2
```

So, wifi powersave is normally disabled in my config...

**Comment by tastyminerals** [comment]
Same issue on `5.3.15-1` :( 
And this is a patched kernel for archlinux which I compiled and installed following [dmhacker instructions](https://github.com/dmhacker/arch-linux-surface)

**Comment by kitakar5525** [comment]
I'm just curious, does changing bt and wifi coexisting mode help for your wifi speed issue?
```bash
Enable timeshare coexistence mode
   echo 1 | sudo tee /sys/kernel/debug/mwifiex/mlan0/timeshare_coex
```

**Comment by jaakkouu** [comment]
> I'm just curious, does changing bt and wifi coexisting mode help for your wifi speed issue?
> 
> ```shell
> Enable timeshare coexistence mode
>    echo 1 | sudo tee /sys/kernel/debug/mwifiex/mlan0/timeshare_coex
> ```

It totally sped up the connection for about 30%. Not good, but much more manageable. Thank you fr that.

Running Ubuntu 20.04 LTS Linux laptop 5.6.14-surface #1 SMP Thu May 21 11:09:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux on my Surface Laptop.

My original speed tested on Windows 10 was about 100mb/s in and out 80mb/s. With current set up I am getting consistent 30mb/s when bluetooth is set off. By switching bluetooth decreases the speed down to 0-1mb/s which is super annoying. Every time I download something even regular updates I just turn bluetooth off so that I don't have to wait for ages.

**Comment by felipetavares** [comment]
I will try to investigate this issue at the driver level, anyone has useful starting pointers for that?

**Comment by FingerlessGlov3s** [comment]
I've got similar issue on Surface Laptop 2 , getting between 1-4mbits, sometimes it'll go fast 30-40mbits then back slow again and stays slow for a long time.

Bluetooth on or off, doesn't make any difference. Also tried turning power_save off didn't help.

Arch Linux (Fully updated as of 04/11/2020) using the Arch Repo and install via the wiki article.

![image](https://user-images.githubusercontent.com/3495647/98169743-bc921880-1ee4-11eb-886b-bbcb5bf2f5ed.png)
