### ISSUE TITLE
Can I select only the necessary patches ?

### ISSUE THREAD

**Issue by prog-amateur** [jakeday/linux-surface#405]
Hello, I installed Debian 10 (named "Buster"), stock Kernel 4.19 on my Surface Pro 3.
 
After installing the Marvel driver (from synaptic >firmware-libertas), everything works except for two things: 

1. Wi-Fi can no longer connect after hibernation (press the power button) 
2. The stylus does not rotate with the display. 

I find the jakeday work fantastic, but I would like to know if it was possible for a beginner like me to select only what I would need to install (in this case, the wifi and stylus patches) since everything else works out-of-the-box? 

Thank you for your feedback and have a good day.

**Comment by tmarkov** [comment]
Both are those problems are resolved via configuration instead of patches. Try this:
1) Install libwacom_0.29-1-surface_amd64.deb from packages/libwacom in this repo
2) Paste the file root/lib/systemd/system-sleep/sleep in this repo to /lib/systemd/system-sleep/

**Comment by prog-amateur** [comment]
Thank you for your kind help. I have tried both solutions (sleep & stylus) but none of them work. 
I have tried on Wayland, System X11, Gnome Xorg. Unfortunately, it was not successful.

**Comment by prog-amateur** [comment]
Help, please

**Comment by korakios** [comment]
sorry for suggesting an obvious option , but did you mark the _sleep_ script as executable after you paste it ?

**Comment by prog-amateur** [comment]
Obvious answer : no ! ^^ Thank you, I was not aware about making the file executable. Now, the Wi-Fi works perfectly after suspending the device ! 

The only thing left is this famous stylus. I don't understand, I installed the libwacom .deb package (with dpkg, because gnome-software crashes on Debian testing) but it doesn't fix the problem of stylus orientation in portrait mode. I have tested Wayland, Xorg, and X11, without success so far. 

Maybe I have forgotten something (as I did for the sleep script)... any idea ?

**Comment by tmarkov** [comment]
Ah, sorry for forgetting that detail.

About stylus, you're right. I just tested it, and I can confirm that libwacom by itself doesn't fix stylus when rotating screen. It may be possible to fix that with configuration, or by fixing the libwacom patch. Weither way, you should probably rename this issue - it's not really about selecting only necessary patches.

**Comment by prog-amateur** [comment]
OK I can't edit the title, so this is what I plan to do : 
The issue with Wi-Fi is closed, so I close this issue. 
I have opened another issue for the stylus, here https://github.com/jakeday/linux-surface/issues/415, so we can try to solve it. 
Thank you very much for your kind help !
